Vagrant.configure("2") do |config|
  config.vm.box = "velocity42/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory="2048"
    vb.cpus="4"
  end
  config.vm.network :forwarded_port, host: 8888, guest: 8888
  config.vm.provision :shell, inline: <<-SHELL
sudo apt-get update
sudo apt-get install -y python-requests python-pandas ipython-notebook
SHELL
config.vm.provision :shell, :inline => "bash /vagrant/run_notebook.sh", run: "always"
end

